import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body className="flex min-h-screen flex-col items-center bg-gradient-to-b from-[#0f0024] to-[#000000] text-white">
        <h1 className="text-5xl font-extrabold tracking-tight text-[hsl(280,46%,65%)] sm:text-[5rem] my-5">
          Algorithm <span className="text-[hsl(280,47%,42%)]">Visualizer</span>
        </h1>
        {children}
      </body>
    </html>
  );
}
